[package]
name = "stronghold-rules-macros"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
license = "Apache-2.0"
description = "Macros for building rules"
homepage = "https://stronghold.docs.iota.org"
repository = "https://github.com/iotaledger/stronghold.rs"

[lib]
name = "macros"
proc-macro = true
path = "src/lib.rs"

[dependencies]
quote       = "1.0.9"
syn         = "1.0.73"
proc-macro2 = "1.0.27"
