[workspace]
members = [
  "engine",
  "engine/runtime",
  "client",
  "utils",
  "derive",
  "p2p",
  "policy"
]
exclude = [
  "products/commandline",
  "products/desktop",
  "products/SHaaS",
  "communication",
]

[profile.release]
overflow-checks = true
panic = "abort"

[profile.dev]
overflow-checks = true
panic = "abort"

[profile.bench]
overflow-checks = true
