[package]
name = "stronghold-policy-derive"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
license = "Apache-2.0"
description = "Derive macros for building policies"
homepage = "https://stronghold.docs.iota.org"
repository = "https://github.com/iotaledger/stronghold.rs"

[lib]
name = "policy_derive"
proc-macro = true
path = "src/lib.rs"

[dependencies.syn]
version = "1.0"
features = ["full"]

[dependencies.quote]
version = "1.0"

[dependencies.proc-macro2]
version = "1.0"